//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DiskServiseLink {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiskServiseLink.IDiskServise")]
    public interface IDiskServise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskServise/GetDiskInfo", ReplyAction="http://tempuri.org/IDiskServise/GetDiskInfoResponse")]
        string[] GetDiskInfo(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskServise/GetDiskInfo", ReplyAction="http://tempuri.org/IDiskServise/GetDiskInfoResponse")]
        System.Threading.Tasks.Task<string[]> GetDiskInfoAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiskServiseChannel : Client.DiskServiseLink.IDiskServise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiskServiseClient : System.ServiceModel.ClientBase<Client.DiskServiseLink.IDiskServise>, Client.DiskServiseLink.IDiskServise {
        
        public DiskServiseClient() {
        }
        
        public DiskServiseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiskServiseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskServiseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskServiseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetDiskInfo(string path) {
            return base.Channel.GetDiskInfo(path);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDiskInfoAsync(string path) {
            return base.Channel.GetDiskInfoAsync(path);
        }
    }
}
