USE School;

CREATE TABLE _Appointment(
    IdAppointment TINYINT IDENTITY PRIMARY KEY,
    NameAppointment NVARCHAR(16) NOT NULL
)

CREATE TABLE _MedicalPaper(
    IdMedicalPaper TINYINT IDENTITY PRIMARY KEY,
	NameMedicalPaper NVARCHAR(32) NOT NULL
)

CREATE TABLE _Role(
	IdRole TINYINT IDENTITY PRIMARY KEY,
	NameRole NVARCHAR(25) NOT NULL
)

CREATE TABLE _Subject(
	IdSubject TINYINT IDENTITY PRIMARY KEY,
	NameSubject NVARCHAR(16) NOT NULL
)
