#ifndef _ERROR_DEF_H_
#define _ERROR_DEF_H_

#define _CRT_SECURE_NO_WARNINGS


#define EXIT_END_OF_MAIN 0

#define ERROR_INPUT_UNKNOWN_EVENT_TYPE -29000
#define ERROR_INPUT_UNTRACKED_INPUT -30000
#define ERROR_INPUT_UNTRACKED_INPUT_MOUSE -31000
#define ERROR_INPUT_NO_INPUT -32000
#define INPUT_RIGHT(a) ((a != ERROR_INPUT_UNKNOWN_EVENT_TYPE) && (a != ERROR_INPUT_UNTRACKED_INPUT) && (a != ERROR_INPUT_UNTRACKED_INPUT_MOUSE) && (a != ERROR_INPUT_NO_INPUT) && (a != NULL) /*NULL if key untracked by ReadConsoleInputA*/ ) 

#endif // !_ERROR_DEF_H_
